services:
  - type: web
    name: granite-oliver-smith
    runtime: ruby
    branch: main
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: granite-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    buildCommand: ./bin/build_script
    startCommand: bundle exec puma -C config/puma.rb

databases:
  - name: granite-db
    databaseName: granite_prod_db
    user: admin
    plan: free
    postgresMajorVersion: "14"

version: "1"
